# Generated by Django 5.1 on 2025-02-13 18:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('transit_hub', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transportation_schedules',
            fields=[
                ('schedule_id', models.AutoField(primary_key=True, serialize=False)),
                ('departure_time', models.DateTimeField()),
                ('arrival_time', models.DateTimeField()),
                ('schedule_status', models.BooleanField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('bus', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='transit_hub.bus')),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='transit_hub.driver')),
                ('route', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='transit_hub.route')),
            ],
            options={
                'verbose_name_plural': 'Transportation Schedules',
                'unique_together': {('schedule_id', 'route', 'bus', 'driver')},
            },
        ),
    ]
