# Generated by Django 5.1.6 on 2025-06-06 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transport_manager', '0003_transportation_schedules_audience_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transportation_schedules',
            name='days',
            field=models.JSONField(default=list, help_text="List of days (e.g. ['monday', 'wednesday'])"),
        ),
    ]
