# Generated by Django 5.1.6 on 2025-06-06 16:26

import multiselectfield.db.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transport_manager', '0004_transportation_schedules_days'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transportation_schedules',
            name='days',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('monday', 'Monday'), ('tuesday', 'Tuesday'), ('wednesday', 'Wednesday'), ('thursday', 'Thursday'), ('friday', 'Friday'), ('saturday', 'Saturday'), ('sunday', 'Sunday')], help_text='Select multiple days', max_length=56),
        ),
    ]
