# Generated by Django 5.1.6 on 2025-06-06 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transport_manager', '0005_alter_transportation_schedules_days'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transportation_schedules',
            name='departure_time',
            field=models.TimeField(),
        ),
    ]
