# Generated by Django 5.1.6 on 2025-07-25 09:47

import multiselectfield.db.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transport_manager', '0006_alter_transportation_schedules_departure_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transportation_schedules',
            name='days',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('monday', 'Monday'), ('tuesday', 'Tuesday'), ('wednesday', 'Wednesday'), ('thursday', 'Thursday'), ('friday', 'Friday'), ('saturday', 'Saturday'), ('sunday', 'Sunday')], default=['monday', 'tuesday', 'wednesday', 'thursday', 'saturday', 'sunday'], help_text='Select multiple days', max_length=56),
        ),
    ]
