# Generated by Django 5.1.6 on 2025-07-25 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transport_manager', '0007_alter_transportation_schedules_days'),
    ]

    operations = [
        migrations.AddField(
            model_name='transportation_schedules',
            name='estimated_end_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
