# Generated by Django 5.1.6 on 2025-11-20 14:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transit_hub', '0015_helper'),
        ('transport_manager', '0008_transportation_schedules_estimated_end_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='transportation_schedules',
            name='helper',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='transit_hub.helper'),
        ),
    ]
