# Generated by Django 5.1.6 on 2025-11-20 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transport_manager', '0009_transportation_schedules_helper'),
    ]

    operations = [
        migrations.AddField(
            model_name='transportation_schedules',
            name='trip_type',
            field=models.CharField(choices=[('one_time', 'One Time'), ('fixed_route', 'Fixed Route')], default='one_time', max_length=20),
        ),
    ]
