# Generated by Django 5.1.6 on 2025-11-22 05:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transit_hub', '0016_driver_total_buses_assigned'),
        ('transport_manager', '0011_locationdata'),
    ]

    operations = [
        migrations.AddField(
            model_name='locationdata',
            name='driver',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='transit_hub.driver'),
        ),
    ]
