# Generated by Django 5.1.6 on 2025-11-24 14:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transport_manager', '0012_locationdata_driver'),
    ]

    operations = [
        migrations.CreateModel(
            name='TripInstance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('actual_start_time', models.DateTimeField(blank=True, null=True)),
                ('actual_end_time', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('schedule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trip_instances', to='transport_manager.transportation_schedules')),
            ],
            options={
                'verbose_name_plural': 'Trip Instances',
                'ordering': ['-date', 'schedule__departure_time'],
                'unique_together': {('schedule', 'date')},
            },
        ),
        migrations.CreateModel(
            name='BusLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('speed', models.FloatField(blank=True, help_text='Speed in km/h', null=True)),
                ('heading', models.FloatField(blank=True, help_text='Direction in degrees', null=True)),
                ('accuracy', models.FloatField(blank=True, help_text='GPS accuracy in meters', null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('trip_instance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='location_history', to='transport_manager.tripinstance')),
            ],
            options={
                'verbose_name_plural': 'Bus Locations',
                'ordering': ['-timestamp'],
            },
        ),
    ]
