# Generated by Django 5.1.6 on 2025-11-24 15:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transport_manager', '0013_tripinstance_buslocation'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BusLocation',
        ),
    ]
