services:
  - type: web
    name: transportation-backend
    env: python
    region: oregon
    plan: free
    branch: main
    buildCommand: |
      pip install -r requirements.txt
      python manage.py collectstatic --noinput
    startCommand: gunicorn transportation_system.wsgi:application --bind 0.0.0.0:$PORT
    envVars:
      - key: DB_NAME
        value: railway
      - key: DB_USER
        value: root
      - key: DB_PASSWORD
        # value omitted — set securely in Render Dashboard environment variables
      - key: DB_HOST
        value: shortline.proxy.rlwy.net
      - key: DB_PORT
        value: "27158"
      - key: SECRET_KEY
        # value omitted — set securely in Render Dashboard environment variables
      - key: DEBUG
        value: 'False'
    autoDeploy: true
    healthCheckPath: /health/
