# Generated by Django 5.1 on 2025-02-12 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bus_name', models.CharField(max_length=30)),
                ('bus_number', models.CharField(max_length=30)),
                ('bus_model', models.CharField(max_length=30)),
                ('bus_capacity', models.IntegerField()),
                ('bus_photo', models.ImageField(upload_to='bus_photos')),
                ('bus_status', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('phone_number', models.CharField(max_length=15)),
                ('license_number', models.CharField(max_length=30)),
                ('license_expiry', models.DateField()),
                ('license_class', models.CharField(max_length=10)),
                ('license_country', models.CharField(max_length=30)),
                ('license_issued', models.DateField()),
                ('license_photo', models.ImageField(upload_to='license_photos')),
                ('driver_photo', models.ImageField(upload_to='driver_photos')),
                ('driver_status', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Route',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('route_name', models.CharField(max_length=30)),
                ('route_number', models.CharField(max_length=30)),
                ('route_distance', models.FloatField()),
                ('route_duration', models.FloatField()),
                ('route_status', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
