# Generated by Django 5.1 on 2025-02-13 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transit_hub', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stopage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stopage_name', models.CharField(max_length=30, unique=True)),
                ('stopage_status', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='route',
            name='route_distance',
        ),
        migrations.RemoveField(
            model_name='route',
            name='route_duration',
        ),
        migrations.AlterField(
            model_name='driver',
            name='driver_photo',
            field=models.ImageField(blank=True, null=True, upload_to='driver_photos'),
        ),
        migrations.AlterField(
            model_name='driver',
            name='license_photo',
            field=models.ImageField(blank=True, null=True, upload_to='license_photos'),
        ),
        migrations.AddField(
            model_name='route',
            name='route_details',
            field=models.ManyToManyField(to='transit_hub.stopage'),
        ),
    ]
