# Generated by Django 5.1 on 2025-02-15 07:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transit_hub', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stoppage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stoppage_name', models.CharField(max_length=100, unique=True)),
                ('stoppage_status', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='route',
            name='route_distance',
        ),
        migrations.RemoveField(
            model_name='route',
            name='route_duration',
        ),
        migrations.AddField(
            model_name='route',
            name='from_dsc',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='route',
            name='to_dsc',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='bus',
            name='bus_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='driver',
            name='driver_photo',
            field=models.ImageField(blank=True, null=True, upload_to='driver_photos'),
        ),
        migrations.AlterField(
            model_name='driver',
            name='license_photo',
            field=models.ImageField(blank=True, null=True, upload_to='license_photos'),
        ),
        migrations.AlterField(
            model_name='route',
            name='route_name',
            field=models.CharField(max_length=100),
        ),
        migrations.CreateModel(
            name='RouteStoppage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField()),
                ('route', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='transit_hub.route')),
                ('stoppage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='transit_hub.stoppage')),
            ],
            options={
                'ordering': ['created_at'],
                'unique_together': {('route', 'created_at')},
            },
        ),
    ]
