# Generated by Django 5.1 on 2025-02-15 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transit_hub', '0004_alter_routestoppage_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='routestoppage',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
