# Generated by Django 5.1 on 2025-02-15 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transit_hub', '0007_alter_routestoppage_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='route',
            name='from_dsc',
            field=models.BooleanField(default=False, verbose_name='From DSC'),
        ),
        migrations.AlterField(
            model_name='route',
            name='to_dsc',
            field=models.BooleanField(default=False, verbose_name='To DSC'),
        ),
    ]
