# Generated by Django 5.1.6 on 2025-07-24 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transit_hub', '0008_alter_route_from_dsc_alter_route_to_dsc'),
    ]

    operations = [
        migrations.AddField(
            model_name='bus',
            name='bus_tag',
            field=models.CharField(blank=True, max_length=30, null=True, unique=True),
        ),
    ]
