# Generated by Django 5.1.6 on 2025-07-25 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transit_hub', '0009_bus_bus_tag'),
    ]

    operations = [
        migrations.AddField(
            model_name='driver',
            name='route_assigned',
            field=models.BooleanField(default=False),
        ),
    ]
