# Generated by Django 5.1.6 on 2025-07-25 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transit_hub', '0010_driver_route_assigned'),
    ]

    operations = [
        migrations.AddField(
            model_name='bus',
            name='bus_assigned',
            field=models.BooleanField(default=False),
        ),
    ]
