# Generated by Django 5.1.6 on 2025-07-25 20:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transit_hub', '0011_bus_bus_assigned'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bus',
            old_name='bus_assigned',
            new_name='route_assigned',
        ),
        migrations.RenameField(
            model_name='driver',
            old_name='route_assigned',
            new_name='bus_assigned',
        ),
    ]
