# Generated by Django 5.1.6 on 2025-11-07 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transit_hub', '0013_remove_driver_first_name_remove_driver_last_name_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='bus',
            unique_together={('bus_name', 'bus_number', 'bus_tag')},
        ),
        migrations.AlterField(
            model_name='bus',
            name='bus_photo',
            field=models.ImageField(blank=True, null=True, upload_to='bus_photos'),
        ),
    ]
