# Generated by Django 5.1.6 on 2025-11-20 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transit_hub', '0014_alter_bus_unique_together_alter_bus_bus_photo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Helper',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('phone_number', models.CharField(max_length=15)),
                ('helper_photo', models.ImageField(blank=True, null=True, upload_to='helper_photos')),
                ('helper_status', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('bus_assigned', models.BooleanField(default=False)),
            ],
            options={
                'unique_together': {('phone_number',)},
            },
        ),
    ]
