# Generated by Django 5.1.6 on 2025-11-20 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transit_hub', '0015_helper'),
    ]

    operations = [
        migrations.AddField(
            model_name='driver',
            name='total_buses_assigned',
            field=models.IntegerField(default=0),
        ),
    ]
