# Generated by Django 5.1.6 on 2025-11-22 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transit_hub', '0016_driver_total_buses_assigned'),
    ]

    operations = [
        migrations.RenameField(
            model_name='driver',
            old_name='total_buses_assigned',
            new_name='total_trip_assigned',
        ),
        migrations.RemoveField(
            model_name='driver',
            name='bus_assigned',
        ),
        migrations.AddField(
            model_name='driver',
            name='total_trip_completed',
            field=models.IntegerField(default=0),
        ),
    ]
