# Generated by Django 5.1.6 on 2025-11-23 17:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transit_hub', '0017_rename_total_buses_assigned_driver_total_trip_assigned_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Short title for the notice', max_length=200)),
                ('message', models.TextField(help_text='Notice message content')),
                ('notice_type', models.CharField(choices=[('info', 'Information'), ('warning', 'Warning'), ('urgent', 'Urgent'), ('maintenance', 'Maintenance')], default='info', max_length=20)),
                ('is_active', models.BooleanField(default=True, help_text='Whether this notice should be displayed')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('expires_at', models.DateTimeField(blank=True, help_text='Notice will auto-hide after this time', null=True)),
                ('route', models.ForeignKey(blank=True, help_text='Leave empty for global notice, or select specific route', null=True, on_delete=django.db.models.deletion.CASCADE, to='transit_hub.route')),
            ],
            options={
                'verbose_name': 'Notice',
                'verbose_name_plural': 'Notices',
                'ordering': ['-created_at'],
            },
        ),
    ]
