# Generated by Django 5.1 on 2025-02-10 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='supervisor',
            name='is_superuser',
            field=models.BooleanField(default=False),
        ),
    ]
