# Generated by Django 5.1.6 on 2025-06-17 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0010_alter_student_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='semester_enrolled',
        ),
        migrations.AddField(
            model_name='student',
            name='batch_code',
            field=models.CharField(default='221', max_length=5),
        ),
    ]
