# Generated by Django 5.1.6 on 2025-06-18 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0011_remove_student_semester_enrolled_student_batch_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='batch_code',
            field=models.CharField(max_length=5),
        ),
    ]
