# Generated by Django 5.1.6 on 2025-07-06 06:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0013_student_is_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='is_active',
        ),
    ]
