# Generated by Django 5.1.6 on 2025-08-11 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0014_remove_student_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='verified',
            field=models.BooleanField(default=False),
        ),
    ]
