# Generated by Django 5.1.6 on 2025-10-25 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0017_student_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='profile_pic',
            field=models.ImageField(default='media/meerkat.png', upload_to='student_profiles/'),
        ),
    ]
