# Generated by Django 5.1.6 on 2025-11-25 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0022_studentreview'),
    ]

    operations = [
        migrations.AddField(
            model_name='preference',
            name='last_searched',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
