# Generated by Django 5.1.6 on 2025-12-02 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0024_supportticket_ticketmessage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='supportticket',
            name='priority',
        ),
        migrations.AddField(
            model_name='supportticket',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='support_tickets/'),
        ),
    ]
