# Generated by Django 5.1.6 on 2025-12-02 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0025_remove_supportticket_priority_supportticket_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supportticket',
            name='category',
            field=models.CharField(blank=True, choices=[('bus_schedule', 'Bus Schedule'), ('route_issue', 'Route Issue'), ('driver_behavior', 'Driver Behavior'), ('bus_condition', 'Bus Condition'), ('payment', 'Payment'), ('account', 'Account'), ('other', 'Other')], default='other', max_length=50),
        ),
    ]
