# Generated by Django 5.1.6 on 2025-12-02 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0027_studentloginactivity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentloginactivity',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='studentloginactivity',
            name='longitude',
        ),
        migrations.AddField(
            model_name='studentloginactivity',
            name='location',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
